apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claim-insurance-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: claim-insurance-app
  project: tenants
  source:
    path: lab-materials/05/app
    repoURL: https://github.com/rh-aiservices-bu/parasol-insurance.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions: [CreateNamespace=false]